"""Compile player-facing draft bodies. Author instructions never enter the game bundle."""
from pathlib import Path
import re, json, html
ROOT = Path(__file__).resolve().parent.parent

def inline(text):
    text = html.escape(text)
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    text = re.sub(r'`(.+?)`', r'<code>\1</code>', text)
    return text

def render(md):
    lines = md.strip().splitlines(); out = []; i = 0
    while i < len(lines):
        line = lines[i].strip()
        if not line: i += 1; continue
        if line.startswith('|'):
            rows = []
            while i < len(lines) and lines[i].strip().startswith('|'):
                cells = [v.strip() for v in lines[i].strip().strip('|').split('|')]
                if not all(re.fullmatch(r':?-+:?', c) for c in cells): rows.append(cells)
                i += 1
            out.append('<div class="story-table-scroll"><table><thead><tr>' + ''.join('<th>'+inline(c)+'</th>' for c in rows[0]) + '</tr></thead><tbody>' + ''.join('<tr>'+''.join('<td>'+inline(c)+'</td>' for c in row)+'</tr>' for row in rows[1:]) + '</tbody></table></div>')
            continue
        if line.startswith('### '): out.append('<h3>'+inline(line[4:])+'</h3>')
        elif line.startswith('> '): out.append('<blockquote>'+inline(line[2:])+'</blockquote>')
        else: out.append('<p>'+inline(line)+'</p>')
        i += 1
    return '\n'.join(out)

docs = {}
for p in sorted((ROOT / 'docs/document-drafts').glob('*.md')):
    if p.name[:2] not in ['01','02','03','04','05','06','07','08','09','10','11','12','14','17','18']: continue
    for m in re.finditer(r'^## ([A-Z][A-Z0-9-]+)｜([^\n]+)\n(.*?)(?=^## |\Z)', p.read_text(), re.M | re.S):
        id, title, content = m.groups()
        if '### 正文初稿\n' not in content: raise ValueError(id)
        body = content.split('### 正文初稿\n',1)[1].split('### 制作备注',1)[0].strip()
        scene = re.search(r'\[?(SC\d\d)', content)
        source = re.search(r'^- 出现：(.+)', content, re.M)
        docs[id] = dict(id=id, title=title, body=render(body), scene=scene[1] if scene else '', draft=p.name, source=source[1] if source else '原件留存')
assert len(docs) == 90, len(docs)
(ROOT/'story-documents.js').write_text('// Generated by scripts/build-story-documents.py; edit the source drafts, then rebuild.\nwindow.StoryDocuments = '+json.dumps(docs,ensure_ascii=False,indent=2)+';\n')
print(f'Compiled {len(docs)} player-facing documents without author notes.')
